services:
  db:
    image: postgres:16
    container_name: fitnexus-postgres
    restart: unless-stopped
    env_file:
      - ../packages/backend/.env
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fitnexus

  redis:
    image: redis:7-alpine
    container_name: fitnexus-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - fitnexus

volumes:
  pgdata:
  redisdata:


networks:
  fitnexus:
    driver: bridge
